-- Generated from IO-LifeExpectancyChart.pdf (InterNACHI). Re-runnable.
insert into public.life_expectancy (category, component, life_min, life_max)
values
('Adhesives, Caulk & Paint','Caulking (interior & exterior)',5,10),
('Adhesives, Caulk & Paint','Construction Glue',20,20),
('Adhesives, Caulk & Paint','Paint (exterior)',7,10),
('Adhesives, Caulk & Paint','Paint (interior)',10,15),
('Adhesives, Caulk & Paint','Roofing Adhesives/Cements',15,15),
('Adhesives, Caulk & Paint','Sealants',8,8),
('Adhesives, Caulk & Paint','Stains',3,8),
('Appliances','Air Conditioner (window)',5,7),
('Appliances','Compactor (trash)',6,6),
('Appliances','Dehumidifier',8,8),
('Appliances','Dishwasher',9,9),
('Appliances','Disposal (food waste)',12,12),
('Appliances','Dryer Vent  (plastic)',5,5),
('Appliances','Dryer Vent  (steel)',20,20),
('Appliances','Dryer (clothes)',13,13),
('Appliances','Exhaust Fans',10,10),
('Appliances','Freezer',10,20),
('Appliances','Gas Oven',10,18),
('Appliances','Hand Dryer',10,12),
('Appliances','Humidifier (portable)',8,8),
('Appliances','Microwave Oven',9,9),
('Appliances','Range/Oven Hood',14,14),
('Appliances','Electric Range',13,15),
('Appliances','Gas Range',15,17),
('Appliances','Refrigerator',9,13),
('Appliances','Swamp Cooler',5,15),
('Appliances','Washing Machine',5,15),
('Appliances','Whole-House Vacuum System',20,20),
('Cabinetry & Storage','Bathroom Cabinets',50,50),
('Cabinetry & Storage','Closet Shelves',100,100),
('Cabinetry & Storage','Entertainment Center/Home Office',10,10),
('Cabinetry & Storage','Garage/Laundry Cabinets',70,70),
('Cabinetry & Storage','Kitchen Cabinets',50,50),
('Cabinetry & Storage','Medicine Cabinet',25,25),
('Cabinetry & Storage','Modular (stock manufacturing-type)',50,50),
('Ceilings & Walls','Ceramic Tile',70,70),
('Ceilings & Walls','Concrete',75,75),
('Ceilings & Walls','Gypsum',75,75),
('Ceilings & Walls','Wood Paneling',20,50),
('Ceilings & Walls','Suspended Ceiling',25,25),
('Countertops','Concrete',50,50),
('Countertops','Cultured Marble',20,20),
('Countertops','Natural Stone',100,100),
('Countertops','Laminate',20,30),
('Countertops','Resin',10,10),
('Countertops','Tile',100,100),
('Countertops','Wood',100,100),
('Decks','Deck Planks',15,15),
('Decks','Composite',8,25),
('Decks','Structural Wood',10,30),
('Doors','Closet (interior)',100,100),
('Doors','Fiberglass (exterior)',100,100),
('Doors','Fire-Rated Steel (exterior)',100,100),
('Doors','French (interior)',30,50),
('Doors','Screen (exterior)',30,30),
('Doors','Vinyl (exterior)',20,20),
('Doors','Wood (exterior)',100,100),
('Doors','Wood (hollow-core interior)',20,30),
('Doors','Wood (solid-core interior)',30,100),
('Electrical','Accessories',10,10),
('Electrical','Arc-Fault Circuit Interrupters (AFCIs)',30,30),
('Electrical','Bare Copper',100,100),
('Electrical','Copper-Clad Aluminum',100,100),
('Electrical','Copper-Plated',100,100),
('Electrical','Fixtures',40,40),
('Electrical','Ground-Fault Circuit Interrupters (GFCIs) up to',30,30),
('Electrical','Lighting Controls',30,30),
('Electrical','Residential Propane Backup Generators',12,12),
('Electrical','Service Panel',60,60),
('Electrical','Solar Panels',20,30),
('Electrical','Solar System Batteries',3,12),
('Electrical','Wind Turbine Generators',20,20),
('Engineered Lumber','Engineered Joists',80,80),
('Engineered Lumber','Laminated Strand Lumber',100,100),
('Engineered Lumber','Laminated Veneer Lumber',80,80),
('Engineered Lumber','Trusses',100,100),
('Fasteners, Connectors & Steel','Adjustable Steel Columns',50,50),
('Fasteners, Connectors & Steel','Fasteners (bright)',25,60),
('Fasteners, Connectors & Steel','Fasteners (copper)',65,80),
('Fasteners, Connectors & Steel','Fasteners (galvanized)',10,10),
('Fasteners, Connectors & Steel','Fasteners (electro-galvanized)',15,45),
('Fasteners, Connectors & Steel','Fasteners (hot-dipped galvanized)',35,60),
('Fasteners, Connectors & Steel','Fasteners (stainless)',65,100),
('Fasteners, Connectors & Steel','Steel Beams',200,200),
('Fasteners, Connectors & Steel','Steel Columns',100,100),
('Fasteners, Connectors & Steel','Steel Plates',100,100),
('Flooring','All Wood Floors',100,100),
('Flooring','Bamboo',100,100),
('Flooring','Brick Pavers',100,100),
('Flooring','Carpet',8,10),
('Flooring','Concrete',50,50),
('Flooring','Engineered Wood',50,50),
('Flooring','Exotic Wood',100,100),
('Flooring','Granite',100,100),
('Flooring','Laminate',15,25),
('Flooring','Linoleum',25,25),
('Flooring','Marble',100,100),
('Flooring','Other Domestic Wood',100,100),
('Flooring','Slate',100,100),
('Flooring','Terrazzo',75,75),
('Flooring','Tile',75,100),
('Flooring','Vinyl',25,25),
('Foundations','Baseboard Waterproofing System',50,50),
('Foundations','Bituminous-Coating Waterproofing',10,10),
('Foundations','Concrete Block',100,100),
('Foundations','Insulated Concrete Forms (ICFs)',100,100),
('Foundations','Permanent Wood Foundation (PWF; treated)',75,75),
('Foundations','Post and Pier',20,65),
('Foundations','Post and Tensioned Slab on Grade',100,100),
('Foundations','Poured-Concrete Footings and Foundation',100,100),
('Foundations','Slab on Grade (concrete)',100,100),
('Foundations','Wood Foundation',5,40),
('Framing','Log',80,200),
('Framing','Poured-Concrete Systems',100,100),
('Framing','Steel',100,100),
('Framing','Structural Insulated Panels (SIPs)',100,100),
('Framing','Timber Frame',100,100),
('Home Technology','Built-In Audio',20,20),
('Home Technology','Carbon Monoxide Detectors*',5,5),
('Home Technology','Doorbells',45,45),
('Home Technology','Home Automation System',5,50),
('Home Technology','Intercoms',20,20),
('Home Technology','Security System',5,20),
('Home Technology','Smoke/Heat Detectors* less than',10,10),
('Home Technology','Wireless Home Networks',5,5),
('Garages','Garage Doors',20,25),
('Garages','Garage Door Openers',10,15),
('HVAC','Air Conditioner (central)',7,15),
('HVAC','Air Exchanger',15,15),
('HVAC','Attic Fan',15,25),
('HVAC','Boiler',40,40),
('HVAC','Burner',10,10),
('HVAC','Ceiling Fan',5,10),
('HVAC','Chimney Cap (concrete)',100,100),
('HVAC','Chimney Cap (metal)',10,20),
('HVAC','Chimney Cap (mortar)',15,15),
('HVAC','Chimney Flue Tile',40,120),
('HVAC','Condenser',8,20),
('HVAC','Dampers',20,20),
('HVAC','Dehumidifier',8,8),
('HVAC','Diffusers, Grilles and Registers',25,25),
('HVAC','Ducting',60,100),
('HVAC','Electric Radiant Heater',40,40),
('HVAC','Evaporative Cooler',15,25),
('HVAC','Furnace',15,25),
('HVAC','Gas Fireplace',15,25),
('HVAC','Heat Exchanger',10,15),
('HVAC','Heat Pump',10,15),
('HVAC','Heat-Recovery Ventilator',20,20),
('HVAC','Hot-Water and Steam-Radiant Boiler',40,40),
('HVAC','Humidifier',12,12),
('HVAC','Induction and Fan-Coil Units',10,15),
('HVAC','Thermostats',35,35),
('HVAC','Ventilator',7,7),
('Insulation & Infiltration Barriers','Batts/Rolls',100,100),
('Insulation & Infiltration Barriers','Black Paper (felt paper)',15,30),
('Insulation & Infiltration Barriers','Cellulose',100,100),
('Insulation & Infiltration Barriers','Fiberglass',100,100),
('Insulation & Infiltration Barriers','Foamboard',100,100),
('Insulation & Infiltration Barriers','Housewrap',80,80),
('Insulation & Infiltration Barriers','Liquid-Applied Membrane',50,50),
('Insulation & Infiltration Barriers','Loose-Fill',100,100),
('Insulation & Infiltration Barriers','Rockwool',100,100),
('Insulation & Infiltration Barriers','Wrap Tape',80,80),
('Masonry & Concrete','Brick',100,100),
('Masonry & Concrete','Insulated Concrete Forms (hybrid block)',100,100),
('Masonry & Concrete','Concrete Masonry Units (CMUs)',100,100),
('Masonry & Concrete','Man-Made Stone',25,25),
('Masonry & Concrete','Masonry Sealant',2,20),
('Masonry & Concrete','Stone',100,100),
('Masonry & Concrete','Stucco/EIFS',50,50),
('Masonry & Concrete','Veneer',100,100),
('Molding, Millwork & Trim','Attic Stairs (pull-down)',50,50),
('Molding, Millwork & Trim','Custom Millwork',100,100),
('Molding, Millwork & Trim','Pre-Built Stairs',100,100),
('Molding, Millwork & Trim','Stair Parts',100,100),
('Molding, Millwork & Trim','Stairs',100,100),
('Panels','Flooring Underlayment',25,25),
('Panels','Hardboard',40,40),
('Panels','Particleboard',60,60),
('Panels','Plywood',100,100),
('Panels','Softwood',30,30),
('Panels','Oriented Strand Board (OSB)',60,60),
('Panels','Wall Panels',100,100),
('Plumbing, Fixtures & Faucets','ABS and PVC Waste Pipe',50,80),
('Plumbing, Fixtures & Faucets','Accessible/ADA Handles',100,100),
('Plumbing, Fixtures & Faucets','Acrylic Kitchen Sink',50,50),
('Plumbing, Fixtures & Faucets','Cast-Iron Bathtub',100,100),
('Plumbing, Fixtures & Faucets','Cast-Iron Waste Pipe (above ground)',60,60),
('Plumbing, Fixtures & Faucets','Cast-Iron Waste Pipe (below ground)',50,60),
('Plumbing, Fixtures & Faucets','Concrete Waste Pipe',100,100),
('Plumbing, Fixtures & Faucets','Copper Water Lines',70,70),
('Plumbing, Fixtures & Faucets','Enameled Steel Kitchen Sink',5,10),
('Plumbing, Fixtures & Faucets','Faucets and Spray Hose',15,20),
('Plumbing, Fixtures & Faucets','Fiberglass Bathtub and Shower',20,20),
('Plumbing, Fixtures & Faucets','Gas Lines (black steel)',75,75),
('Plumbing, Fixtures & Faucets','Gas Lines (flex)',30,30),
('Plumbing, Fixtures & Faucets','Hose Bibs',20,30),
('Plumbing, Fixtures & Faucets','Instant (on-demand) Water Heater',10,10),
('Plumbing, Fixtures & Faucets','PEX',40,40),
('Plumbing, Fixtures & Faucets','Plastic Water Lines',75,75),
('Plumbing, Fixtures & Faucets','Saunas/Steam Room',15,20),
('Plumbing, Fixtures & Faucets','Sewer Grinder Pump',10,10),
('Plumbing, Fixtures & Faucets','Shower Enclosure/Module',50,50),
('Plumbing, Fixtures & Faucets','Shower Doors',20,20),
('Plumbing, Fixtures & Faucets','Soapstone Kitchen Sink',100,100),
('Plumbing, Fixtures & Faucets','Sump Pump',7,7),
('Plumbing, Fixtures & Faucets','Toilet Tank Components',5,5),
('Plumbing, Fixtures & Faucets (continued)','Toilets, Bidets and Urinals',100,100),
('Plumbing, Fixtures & Faucets (continued)','Vent Fan (ceiling)',5,10),
('Plumbing, Fixtures & Faucets (continued)','Vessel Sink (stone, glass, porcelain, copper)',5,20),
('Plumbing, Fixtures & Faucets (continued)','Water Heater (conventional)',6,12),
('Plumbing, Fixtures & Faucets (continued)','Water Line (copper)',50,50),
('Plumbing, Fixtures & Faucets (continued)','Water Line (plastic)',50,50),
('Plumbing, Fixtures & Faucets (continued)','Water Softener',20,20),
('Plumbing, Fixtures & Faucets (continued)','Well Pump',15,15),
('Plumbing, Fixtures & Faucets (continued)','Whirlpool Tub',20,50),
('Radon Systems','Air Exchanger',15,15),
('Radon Systems','Barometric Backdraft Damper/Fresh-Air Intake',20,20),
('Radon Systems','Caulking',5,10),
('Radon Systems','Labeling',25,25),
('Radon Systems','Manometer',15,15),
('Radon Systems','Piping',50,50),
('Radon Systems','Radon Fan',5,8),
('Roofing','Aluminum Coating',3,7),
('Roofing','Asphalt (architectural)',30,30),
('Roofing','Asphalt Shingles (3-tab)',20,20),
('Roofing','BUR (built-up roofing)',30,30),
('Roofing','Clay/Concrete',100,100),
('Roofing','Coal and Tar',30,30),
('Roofing','Copper',70,70),
('Roofing','EPDM (ethylene propylene diene monomer) Rubber',15,25),
('Roofing','Fiber Cement',25,25),
('Roofing','Green (vegetation-covered)',5,40),
('Roofing','Metal',40,80),
('Roofing','Modified Bitumen',20,20),
('Roofing','Simulated Slate',10,35),
('Roofing','Slate',60,150),
('Roofing','TPO',7,20),
('Roofing','Wood',25,25),
('Sidings, Flashings & Accessories','Aluminum Gutters, Downspouts, Soffit and Fascia',20,40),
('Sidings, Flashings & Accessories','Aluminum Siding',25,40),
('Sidings, Flashings & Accessories','Asbestos Shingle',100,100),
('Sidings, Flashings & Accessories','Brick',100,100),
('Sidings, Flashings & Accessories','Cementitious',100,100),
('Sidings, Flashings & Accessories','Copper Downspouts',100,100),
('Sidings, Flashings & Accessories','Copper Gutters',50,50),
('Sidings, Flashings & Accessories','Engineered Wood',100,100),
('Sidings, Flashings & Accessories','Fiber Cement',100,100),
('Sidings, Flashings & Accessories','Galvanized Steel Gutters/Downspouts',20,20),
('Sidings, Flashings & Accessories','Manufactured Stone',100,100),
('Sidings, Flashings & Accessories','Stone',100,100),
('Sidings, Flashings & Accessories','Stucco/EIFS',50,50),
('Sidings, Flashings & Accessories','Trim',25,25),
('Sidings, Flashings & Accessories','Vinyl Gutters and Downspouts',25,25),
('Sidings, Flashings & Accessories','Vinyl Siding',60,60),
('Sidings, Flashings & Accessories','Wood/Exterior Shutters',20,20),
('Site & Landscaping','Asphalt Driveway',15,20),
('Site & Landscaping','Brick and Concrete Patio',15,25),
('Site & Landscaping','Clay Paving',100,100),
('Site & Landscaping','Concrete Walks',40,50),
('Site & Landscaping','Controllers',15,15),
('Site & Landscaping','Gravel Walks',4,6),
('Site & Landscaping','Mulch',1,2),
('Site & Landscaping','Polyvinyl Fencing',100,100),
('Site & Landscaping','Sprinkler Heads',10,14),
('Site & Landscaping','Underground PVC Piping',60,60),
('Site & Landscaping','Valves',20,20),
('Site & Landscaping','Wood Chips',1,5),
('Site & Landscaping','Wood Fencing',20,20),
('Swimming Pools','Concrete Shell',25,25),
('Swimming Pools','Cover',7,7),
('Swimming Pools','Diving Board',10,10),
('Swimming Pools','Filter and Pump',10,10),
('Swimming Pools','Interior Finish',10,35),
('Swimming Pools','Pool Water Heater',8,8),
('Swimming Pools','Vinyl Liner',10,10),
('Swimming Pools','Waterline Tile',15,15),
('Windows','Aluminum/Aluminum-Clad',15,20),
('Windows','Double-Pane',8,20),
('Windows','Skylights',10,20),
('Windows','Vinyl/Fiberglass Windows',20,40),
('Windows','Window Glazing',10,10),
('Windows','Wood',30,30)
on conflict (category, component) do update set
  life_min = excluded.life_min, life_max = excluded.life_max;
